// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jffyeovlgrdcevfnvyxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmZnllb3ZsZ3JkY2V2Zm52eXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTI1OTcsImV4cCI6MjA2NTE2ODU5N30.PAY_ZDjhLRyKwFMJwwtto2ghseqNV_a-wBC1u5EccxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);